# Generated by Django 4.2.3 on 2023-08-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='address',
            new_name='location',
        ),
    ]
